name: Trigger Workspace Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger-workspace:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Debug Info
        run: |
          echo "Triggering repository: garage44/workspace"
          echo "Event type: expressio-update"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub SHA: ${{ github.sha }}"

      - name: Trigger Workspace Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.WORKSPACE_REPO_TOKEN }}
          repository: garage44/workspace
          event-type: expressio-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Check Response
        if: success()
        run: echo "Successfully triggered workflow"